apiVersion: apps/v1

kind: Deployment

metadata:

  name: weather-app

  labels:

    app: weather

spec:

  replicas: 2

  selector:

    matchLabels:

      app: weather

  template:

    metadata:

      labels:

        app: weather

    spec:

      containers:

      - name: weather

        image: nadavalon/weather_cont:weather

        ports:

        - containerPort: 80
